### ISSUE TITLE
Saving todos in project specific org-file

### ISSUE THREAD

**Issue by halbtuerke** [IvanMalison/org-projectile#4]
Hi,

is it possible to configure org-projectile so that it's capturing todos in project specific files in the root of the project?

I have a habit of putting a `todo.org` file into my projects and it would be great if org-projectile would use this file instead of a global org-file.

Thanks in advance

**Comment by IvanMalison** [comment]
I've been thinking about adding this functionality. It shouldn't be hard to do, but as of right now this is not possible. Let me see if I can throw something together quickly to support this.

**Comment by halbtuerke** [comment]
That would be really great!

**Comment by IvanMalison** [comment]
Okay -- I think I've added the behavior that you wanted. It probably needs some work/testing, so if you could give it a whirl that would be great.

Do you use org-agenda at all? Should org-projectile provide a function that lists all existing project files so that they can be added to your agenda files?

**Comment by IvanMalison** [comment]
Oh, so the way you use it is by calling
(org-projectile:per-repo)

You can do this interactively, but i would recommend that you add it to your config.

As of right now, the todos are all filed to the top level.

**Comment by halbtuerke** [comment]
Wow, that was fast! I've played around with this new functionality and as far as I'm concerned it works great. It even created a new `todo.org` in projects where the file wasn't present.

> Do you use org-agenda at all?

Actually no.

> so the way you use it is by calling
> (org-projectile:per-repo)

That I find a little bit weird. Is this on purpose so that one can switch between both ways of adding todos? Otherwise I would suggest to just provide a way to toggle this via an option.

Thank you very much

**Comment by IvanMalison** [comment]
Well I went a little overboard with the generality of this feature, and made it so that you can provide custom functions that basically describe how to find the appropriate location to file org todos, so `org-projectile:per-repo` sets the value of three different variables to appropriate function names which must be set together in order to get the functionality that you described.

calling `(org-projectile:per-repo)` will probably be enough for most people, but what if you want to file things in your main file in most cases, but for one project you want to file inside the repo. This makes it so that you just supply a simple custom definition to acheive this behavior.

One of the reasons that I elected to put everything in one file rather than in separate files is that it is much more difficult to synchronize things over dropbox or whatever if you have per repository files. Just thought I'd mention that in case you plan on doing that at any point in the future.

**Comment by IvanMalison** [comment]
Can I close this issue?

**Comment by halbtuerke** [comment]
> One of the reasons that I elected to put everything in one file rather than in separate files is that it is much more difficult to synchronize things over dropbox or whatever if you have per repository files.

That seem's quite obvious but as my projects are usually version-controlled I put the todo.org file directly into the repo. So no extra syncing efforts there.

> Can I close this issue?

Yes.
