### ISSUE TITLE
`org-projectile-goto-location-for-project` should default to current project?

### ISSUE THREAD

**Issue by Lenbok** [IvanMalison/org-projectile#57]
Perhaps it's because I'm using vertico etc, but when I invoke `org-projectile-goto-location-for-project`, I get a prompt like:

```
[projectA] Select which project's TODOs you would like to go to:><
projectC
projectD
projectE
projectA
projectB
[...]
```
It "knows" the current project is `projectA`, but that is not prefilled as a completion default at `><`, and I have to explicitly select from the completion candidates.

**Comment by IvanMalison** [comment]
When you say invoke, do you mean call using e.g. M-x?

This is because of how the interactive is defined for this function.

If you want to go to the current projects location, you could define a new function that uses the current project.

`(org-projectile-goto-location-for-project (projectile-project-name))`

**Comment by Lenbok** [comment]
Thank you, I'm now using your suggested function instead of interactive selection. It's a shame that the interactive method can't select the default appropriately though.

**Comment by IvanMalison** [comment]
> Thank you, I'm now using your suggested function instead of interactive selection. It's a shame that the interactive method can't select the default appropriately though.

Actually it can, its the second argument to projectile-completing-read

if you want this:

```
(defun org-projectile-goto-location-for-project (project)
  "Goto the location at which TODOs for PROJECT are stored."
  (interactive
   (list
    (projectile-completing-read
     "Select which project's TODOs you would like to go to: "
     (occ-get-categories org-projectile-strategy) :initial-input (projectile-project-name))))
  (occ-capture-goto-marker
   (make-instance 'occ-context
                  :category project
                  :template org-projectile-capture-template
                  :strategy org-projectile-strategy
                  :options nil)))
```

Personally im not a fan because its not clear that there a bunch of options ot choose from because the selection is already narrowed. If you want to go to the current proejct thats easy enough with the elisp i gave you, so i wont make this change in the official definition

**Comment by rileyrg** [comment]
Oh, I just raised an issue on this. If I'm in a project then I would expect org-project-capture to default to that project. I'll try and get suggestions about to work, but a boolean to default this behaviour would be nice - it seems kind of how it should work.
