### ISSUE TITLE
Perhaps tag a release?

### ISSUE THREAD

**Issue by mdorman** [IvanMalison/org-projectile#8]
There haven't been any changes in a couple of weeks---things seem to be settling down.  Perhaps tag a release so melpa-stable can pick it up, so people don't necessarily have to set themselves up for the bleeding edge on melpa?

**Comment by IvanMalison** [comment]
I haven't submitted a recipe for melpa stable, but I just bumped the minor version number. Feel free to submit the recipe your self (this comment should be considered official approval for org-projectile's placement on melpa stable).

**Comment by mdorman** [comment]
In fact, I believe melpa-stable *should* pick it up automatically.  But thanks for also explicitly approving, too.  I'll close the issue when it shows up.

**Comment by mdorman** [comment]
Sorry, I didn't notice until now---melpa-stable won't pick it up until you actually tag the release in git.

**Comment by IvanMalison** [comment]
Ahh yeah that make sense. Made the tag. Are you sure you want to use melpa-stable for this package? It has broken twice now because of tweaks to the org-mode logic. I've been pretty good about putting out a quick fix (since this package is pretty essential to my own org workflow). I guess I can just make sure to make a patch version bump in those cases in the future.

I guess I have put out slightly breaking changes on a couple occassions...

**Comment by mdorman** [comment]
Your points are very reasonable---the emacs package ecosystem is still immature in regards to keeping all that sort of stuff straight.  And it might all prove unworkable, I dunno.  But I have had enough random breakage from following bleeding-edge development on melpa that it seems worth a try to see if we can't start to make things a little more predictable.

So for the packages I'm using---and BTW, thanks for writing org-projectile, it's very handy (and I have a doc suggestion I need to put into a PR)---at least, I figure I should at least try and work with maintainers to see if it can be done.

**Comment by IvanMalison** [comment]
Looks like its on melpa stable.

**Comment by mdorman** [comment]
Yep.
